hcaec/hcaec/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mybog.urls')),
    
]

hcaec/mybog/urls.py
from django.urls import path
from . import views

app_name='mybog'

urlpatterns = [
    path('', views.index, name='index'),
    path('about', views.about, name='about'),
    path('service', views.service, name='service'),
    path('contact', views.contact, name='contact'),
    path('university', views.university, name='university'),
    path('apply', views.apply, name='apply'),
    path('blog', views.blog, name='blog'),
    path('blogdetail/<post_id>', views.blogdetail, name='blogdetail'),
]

hcaec/mybog/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Clients(models.Model):
    name = models.CharField(max_length = 250)
    email= models.EmailField()
    subject = models.CharField(max_length = 250)
    message = models.TextField()

    def __str__(self):
        return self.name
    
class Post(models.Model):
    title = models.CharField(max_length = 250)
    author = models.CharField(max_length = 50)
    about = models.CharField(max_length = 50)
    bdy = models.TextField(max_length = 10000)
    date = models.DateTimeField()

    def __str__(self):
        return self.title

class University(models.Model):
    universityName = models.CharField(max_length = 50)
    universityCountry = models.CharField(max_length = 50)
    universityContinent = models.CharField(max_length = 50)
    

    def __str__(self):
       return self.universityName
    
class Student(models.Model):
    studentFirstName = models.CharField(max_length = 50)
    studentMiddleName = models.CharField(max_length = 50)
    studentLastName = models.CharField(max_length = 50)
    studentGender = models.CharField(max_length = 50)
    studentEmail = models.EmailField()
    studentPhone = models.IntegerField()
    studentLevel = models.CharField(max_length = 50)
    studentCourse = models.CharField(max_length = 50)
    studentCountry = models.CharField(max_length = 50, blank=True)
    parentPhone = models.IntegerField()

    def __str__(self):
       return self.studentFirstName + ' ' + self.studentMiddleName + ' ' + self.studentLastName

hcaec/mybog/forms.py
from django import forms
from django.forms import ModelForm
from .models import Clients,Student

class ClientForm(ModelForm):
      class Meta:
            model = Clients
            fields =['name', 'email','subject', 'message']

            labels={
                  'name':'','email':'', 'subject':'', 'message':''
            }

            widgets ={
                  'name':forms.TextInput(attrs={'class':'form-control', 'placeholder':'Your Name'}),
                  'email':forms.EmailInput(attrs={'class':'form-control', 'placeholder':'Your Email'}),
                  'subject':forms.TextInput(attrs={'class':'form-control', 'placeholder':'Subject'}),
                  'message':forms.Textarea(attrs={'class':'form-control', 'placeholder':'Your Message'})  
            }

class ApplyForm(ModelForm):
      class Meta:
            model = Student
            fields =[
                  'studentFirstName', 'studentMiddleName','studentLastName', 'studentGender',
                  'studentEmail','studentPhone','studentLevel','studentCourse','studentCountry', 'parentPhone'
                     ]
            
            labels ={
                  'studentFirstName':'', 'studentMiddleName':'','studentLastName':'', 'studentGender':'',
                  'studentEmail':'','studentPhone':'','studentLevel':'','studentCourse':'','studentUniversity':'',
                   'studentCountry':'','parentFirstNam':'','parenttLastName':'','parentEmail':'','parentPhone':''
                  }
            
            widgets ={
                  'studentFirstName':forms.TextInput(attrs={'class':'form-control', 'placeholder':'First Name'}),
                  'studentMiddleName':forms.TextInput(attrs={'class':'form-control', 'placeholder':'Middle Name'}),
                  'studentLastName':forms.TextInput(attrs={'class':'form-control', 'placeholder':'Last Name'}),
                  'studentGender':forms.TextInput(attrs={'class':'form-control', 'placeholder':'Gender eg. Male or Female'}),
                  'studentEmail':forms.EmailInput(attrs={'class':'form-control', 'placeholder':'Email'}),
                  'studentPhone':forms.NumberInput(attrs={'class':'form-control', 'placeholder':'Phone number'}),
                  'studentLevel':forms.TextInput(attrs={'class':'form-control', 'placeholder':'Desired Level of study eg. Degree, Diploma or Master'}),
                  'studentCourse':forms.TextInput(attrs={'class':'form-control', 'placeholder':'Course'}),  
                  'studentCountry':forms.TextInput(attrs={'class':'form-control', 'placeholder':'Country Name'}),
                  'parentPhone':forms.NumberInput(attrs={'class':'form-control', 'placeholder':'Parent Phone number'}),

            }

hcaec/mybog/views.py
from django.shortcuts import redirect, render
from .forms import ClientForm,ApplyForm
from . models import Post,University
from django.core.paginator import Paginator


# Create your views here.
def index(request):
    post = Post.objects.all().order_by('-id')[:3]
    if request.method == 'POST':
        if request.method == 'POST':
           form = ClientForm(request.POST)
        if form.is_valid():
           form.save()
           return redirect('mybog:index')
    
    else:
        form = ClientForm()
    return render(request, 'mybog/index.html',{'form':form, 'post':post})

def about(request):
    return render(request, 'mybog/about.html')

def blog(request):
    post = Post.objects.all().order_by('-id')
    return render(request, 'mybog/blog.html',{'post':post})

def service(request):
    return render(request, 'mybog/service.html')

def contact(request):
    if request.method == 'POST':
        if request.method == 'POST':
           form = ClientForm(request.POST)
        if form.is_valid():
           form.save()
           return redirect('mybog:contact')
    
    else:
        form = ClientForm()
    return render(request, 'mybog/contact.html',{'form':form})

def university(request):
    p = Paginator(University.objects.all().order_by('-id'),6)
    page = request.GET.get('page')
    university = p.get_page(page)
    return render(request, 'mybog/university.html',{'university':university})

def apply(request):
    if request.method == 'POST':
        form = ApplyForm(request.POST)

        if form.is_valid():
           form.save()
           return redirect('mybog:apply')
    
    else:
        form = ApplyForm()
    return render(request, 'mybog/apply.html',{'form':form})

def blogdetail(request,post_id,):
    post = Post.objects.get(pk=post_id)
    posts = Post.objects.all().order_by('-id')[:5]
    context ={'post':post, 'posts':posts}
    return render(request, 'mybog/blogdetail.html',context)


    

hcaec/mybog/templates/mybog/apply.html
{% extends 'mybog/mylayout.html' %}
{% load static %}

{% block content %}

<main id="main">

    <!-- ======= Breadcrumbs ======= -->
    <div class="breadcrumbs d-flex align-items-center" style="background-image: url('assets/img/breadcrumbs-bg.jpg');">
      <div class="container position-relative d-flex flex-column align-items-center" data-aos="fade">

        <h2>Apply Now</h2>
        <ol>
          <li><a href="{% url 'mybog:index' %}">Home</a></li>
          <li>Apply</li>
        </ol>

      </div>
    </div><!-- End Breadcrumbs -->

<section class="mx-2">
  <div class="mt-2 ms-1 me-1">
    <div class="section-header">
      <h2>Let's Handle Your Application </h2>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Est dolore illo excepturi placeat ea minima. Autem eius facere tenetur impedit?</p>
    </div>
 
    <form class="row g-3" method="POST" action="" class="myform">
        {% csrf_token %}
          <div class="col-md-4">
            {{form.studentFirstName}}
          </div>
          <div class="col-md-4">
            {{form.studentMiddleName}}
          </div>
          <div class="col-md-4">
            {{form.studentLastName}}
          </div>
          <div class="col-md-4">
            {{form.studentGender}}
          </div>
          <div class="col-md-4">
            {{form.studentEmail}}
          </div>
          <div class="col-md-4">
            {{form.studentPhone}}
          </div>
          <div class="col-md-4">
            {{form.studentLevel}}
          </div>
          <div class="col-md-4">
            {{form.studentCourse}}
          </div>
          <div class="col-md-4">
            {{form.studentCountry}}
          </div>
          <div class="col-md-4 mb-3">
            {{form.parentPhone}}
          </div>

          <div class="mx-auto  text-center py-2">
            <button type="submit" class="col-md-3  text-white py-2 bg-warning border border-warning">Apply Now</button>
          </div>

          
    </form>   
  
</div>
</section>

  </main><!-- End #main -->


{% endblock content %}

hcaec/mybog/templates/mybog/blog.html
{% extends 'mybog/mylayout.html' %}
{% load static %}

{% block content %}
<main id="main">

    <!-- ======= Breadcrumbs ======= -->
    <div class="breadcrumbs d-flex align-items-center blogpic">
      <div class="container position-relative d-flex flex-column align-items-center" data-aos="fade">

        <h2>Blog</h2>
        <ol>
          <li><a href="{% url 'mybog:index' %}">Home</a></li>
          <li>Blog</li>
        </ol>

      </div>
    </div><!-- End Breadcrumbs -->

        <!-- ======= Recent Blog Posts Section ======= -->
        <section id="recent-blog-posts" class="recent-blog-posts">
            <div class="container" data-aos="fade-up">
            <div class=" section-header">
              <h2>Recent Blog Posts</h2>
              <p>In commodi voluptatem excepturi quaerat nihil error autem voluptate ut et officia consequuntu</p>
            </div>
      
            <div class="row gy-5">
      
              {% for post in post %}
      
              <div class="col-xl-4 col-md-6" data-aos="fade-up" data-aos-delay="100">
                <div class="post-item position-relative h-100">
      
                  <div class="post-img position-relative">
                    <span class="post-date">{{post.date}}</span>
                  </div>
      
                  <div class="post-content d-flex flex-column">
      
                    <h3 class="post-title">{{post.title}}</h3>
      
                    <div class="meta d-flex align-items-center">
                      <div class="d-flex align-items-center">
                        <i class="bi bi-person"></i> <span class="ps-2">{{post.author}}</span>
                      </div>
                      <span class="px-3 text-black-50">/</span>
                      <div class="d-flex align-items-center">
                        <i class="bi bi-folder2"></i> <span class="ps-2">{{post.about}}</span>
                      </div>
                    </div>
      
                    <hr>
      
                    <a href="{% url 'mybog:blogdetail' post.id %}" class="readmore stretched-link"><span>Read More</span><i class="bi bi-arrow-right"></i></a>
      
                  </div>
      
                </div>
              </div><!-- End post item -->
      
              {% endfor %}
      
            </div>
      
            </div>
          </section>
          <!-- End Recent Blog Posts Section -->
          
</main>
{% endblock content %}

hcaec/mybog/templates/mybog/blogdetail.html
{% extends 'mybog/mylayout.html' %}
{% load static %}

{% block content %}
<main id="main">

    <!-- ======= Breadcrumbs ======= -->
    <div class="breadcrumbs d-flex align-items-center" style="background-image: url('assets/img/breadcrumbs-bg.jpg');">
      <div class="container position-relative d-flex flex-column align-items-center" data-aos="fade">

        <h2>Blog Details</h2>
        <ol>
          <li><a href="{% url 'mybog:index' %}">Home</a></li>
          <li>Blog Details</li>
        </ol>

      </div>
    </div><!-- End Breadcrumbs -->

    <!-- ======= Blog Details Section ======= -->
    <section id="blog" class="blog">
      <div class="container" data-aos="fade-up" data-aos-delay="100">

        <div class="row g-5">

          <div class="col-lg-8">

            <article class="blog-details">
              <h2 class="title">{{post.title}}</h2>

              <div class="meta-top">
                <ul>
                  <li class="d-flex align-items-center"><i class="bi bi-person"></i>{{post.author}}</li>
                  <li class="d-flex align-items-center"><i class="bi bi-folder"></i>{{post.about}}</li>
                  <li class="d-flex align-items-center"><i class="bi bi-clock"></i> {{post.date}}</li>
                </ul>
              </div><!-- End meta top -->

              <div class="content">
                <p>
                    {{post.bdy}}
                </p>

              </div><!-- End post content -->

              <div class="meta-bottom">
                <i class="bi bi-folder"></i>
                <ul class="cats">
                  <li>{{post.about}}</li>
                </ul>
              </div><!-- End meta bottom -->

            </article><!-- End blog post -->

            <div class="post-author d-flex align-items-center">
              <img src="assets/img/blog/blog-author.jpg" class="rounded-circle flex-shrink-0" alt="">
              <div>
                <h4>HCAEC</h4>
                <div class="social-links">
                  <a href="https://twitters.com/#"><i class="bi bi-twitter"></i></a>
                  <a href="https://facebook.com/#"><i class="bi bi-facebook"></i></a>
                  <a href="https://instagram.com/#"><i class="biu bi-instagram"></i></a>
                </div>
                <p>
                  Itaque quidem optio quia voluptatibus dolorem dolor. Modi eum sed possimus accusantium. Quas repellat voluptatem officia numquam sint aspernatur voluptas. Esse et accusantium ut unde voluptas.
                </p>
              </div>
            </div><!-- End post author -->

          </div>

          <div class="col-lg-4">

            <div class="sidebar">

              <div class="sidebar-item recent-posts">
                <h3 class="sidebar-title">Recent Posts</h3>

                <div class="mt-3">
                    {% for posts in posts %}

                  <div class="post-item mt-3">
                    <div>
                      <h4><a href="{% url 'mybog:blogdetail' post.id %}">{{posts.title}}</a></h4>
                      <p>{{posts.date}}</p>
                    </div>
                  </div><!-- End recent post item-->
                   {% endfor %}

                </div>

              </div><!-- End sidebar recent posts-->

              <div class="post-item mt-3">
                <h4 class=""><a href="{% url 'mybog:blog' %}">View All &raquo</a></h4>
              </div><!-- End sidebar tags-->

            </div><!-- End Blog Sidebar -->

          </div>
        </div>

      </div>
    </section><!-- End Blog Details Section -->

  </main><!-- End #main -->


{% endblock content %}

hcaec/mybog/templates/mybog/contact.html
{% extends 'mybog/mylayout.html' %}
{% load static %}

{% block content %}

<main id="main">

    <!-- ======= Breadcrumbs ======= -->
    <div class="breadcrumbs d-flex align-items-center contaimg">
      <div class="container position-relative d-flex flex-column align-items-center" data-aos="fade">

        <h2>Contact</h2>
        <ol>
          <li><a href="{% url 'mybog:index' %}">Home</a></li>
          <li>Contact</li>
        </ol>

      </div>
    </div><!-- End Breadcrumbs -->

      <!-- ======= Contact Section ======= -->
      <section id="contact" class="contact">
        <div class="container" data-aos="fade-up" data-aos-delay="100">
  
          <div class="row gy-4">
            <div class="col-lg-6">
              <div class="info-item  d-flex flex-column justify-content-center align-items-center">
                <i class="bi bi-map"></i>
                <h3>Our Address</h3>
                <p>Makumbusho, Dar Es Salaam, Tanzania</p>
              </div>
            </div><!-- End Info Item -->
  
            <div class="col-lg-3 col-md-6">
              <div class="info-item d-flex flex-column justify-content-center align-items-center">
                <i class="bi bi-envelope"></i>
                <h3>Email Us</h3>
                <p>info@hcaec.co.tz</p>
              </div>
            </div><!-- End Info Item -->
  
            <div class="col-lg-3 col-md-6">
              <div class="info-item  d-flex flex-column justify-content-center align-items-center">
                <i class="bi bi-telephone"></i>
                <h3>Call Us</h3>
                <p>+255 745656 712</p>
              </div>
            </div><!-- End Info Item -->
  
          </div>
  
          <div class="row gy-4 mt-1">
  
            <div class="col-lg-6 ">
              <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d15847.387646392819!2d39.240786672371506!3d-6.788476083901584!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x185c4c0fc3f3bbc9%3A0x7d797376d0ebc3f1!2sMakumbusho%2C%20Dar%20es%20Salaam!5e0!3m2!1sen!2stz!4v1690897730919!5m2!1sen!2stz" frameborder="0" style="border:0; width: 100%; height: 384px;" allowfullscreen></iframe>
            </div><!-- End Google Maps -->
  
            <div class="col-lg-6">
              <form action="" method="post" role="form" class="myform">
                {% csrf_token %}
                <div class="row gy-4">
                  <div class="col-lg-6 form-group">
                    <input type="text" name="name" class="form-control" id="name" placeholder="Your Name" required>
                  </div>
                  <div class="col-lg-6 form-group">
                    <input type="email" class="form-control" name="email" id="email" placeholder="Your Email" required>
                  </div>
                </div>
                <div class="form-group">
                  <input type="text" class="form-control" name="subject" id="subject" placeholder="Subject" required>
                </div>
                <div class="form-group">
                  <textarea class="form-control" name="message" rows="5" placeholder="Message" required></textarea>
                </div>
                <div class="text-center"><button type="submit">Send Message</button></div>
              </form>
            </div><!-- End Contact Form -->
          </div>
  
        </div>
      </section>
  

  </main><!-- End #main -->


{% endblock content %}

hcaec/mybog/templates/mybog/mylayout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>HCAEC</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="assets/img/favicon.png" rel="icon">
  <link href="assets/img/apple-touch-icon.png" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,600;1,700&family=Roboto:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&family=Work+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'mybog/assets/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'mybog/assets/bootstrap/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'mybog/assets/css/main.css' %}" rel="stylesheet">
  <link href="{% static 'mybog/fontawesome-free/css/all.min.css' %}" rel="stylesheet">
  <link href="{% static 'mybog/aos/aos.css' %}" rel="stylesheet">
  <link href="{% static 'mybog/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static 'mybog/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'myblog/assets/css/main.css' %}" rel="stylesheet">
</head>

<body>

  <!-- ======= Header ======= -->
  <header id="header" class="header d-flex align-items-center">
    <div class="container-fluid container-xl d-flex align-items-center justify-content-between">

      <a href="{% url 'mybog:index' %}" class="logo d-flex align-items-center">
        <!-- Uncomment the line below if you also wish to use an image logo -->
        <!-- <img src="assets/img/logo.png" alt=""> -->
        <h1>HK education agency<span>.</span></h1>
      </a>

      <i class="mobile-nav-toggle mobile-nav-show bi bi-list"></i>
      <i class="mobile-nav-toggle mobile-nav-hide d-none bi bi-x"></i>
      <nav id="navbar" class="navbar">
        <ul>
          <li><a href="{% url 'mybog:index' %}" class="active">Home</a></li>
          <li><a href="{% url 'mybog:about' %}">About</a></li>
          <li><a href="{% url 'mybog:service' %}">Services</a></li>
          <li><a href="{% url 'mybog:contact' %}">Contact</a></li>
          <li><a href="{% url 'mybog:blog' %}">Blog</a></li>
          <li><a href="{% url 'mybog:university' %}">Universities</a></li>
          <li><a href="{% url 'mybog:apply' %}" class="btn btn-outline-warning text-white p-2 rounded-pill">Apply Now</a></li>
        </ul>
      </nav><!-- .navbar -->

    </div>
  </header><!-- End Header -->
  {% block content %}


  {% endblock content %}

  <!-- ======= Footer ======= -->
  <footer id="footer" class="footer">

    <div class="footer-content position-relative">
      <div class="container">
        <div class="row">

          <div class="col-lg-4 col-md-6">
            <div class="footer-info">
              <h2>HK education agency</h2>
              <p>
                Makumbusho <br>
                Dar Es Salaam, Tanzania<br><br>
                <strong>Phone:</strong> +255 745656712<br>
                <strong>Email:</strong> info@hcaec.com<br>
              </p>
              <div class="social-links d-flex mt-3">
                <a href="#" class="d-flex align-items-center justify-content-center"><i class="bi bi-twitter"></i></a>
                <a href="#" class="d-flex align-items-center justify-content-center"><i class="bi bi-facebook"></i></a>
                <a href="#" class="d-flex align-items-center justify-content-center"><i class="bi bi-instagram"></i></a>
                <a href="#" class="d-flex align-items-center justify-content-center"><i class="bi bi-linkedin"></i></a>
              </div>
            </div>
          </div><!-- End footer info column-->

          <div class="col-lg-2 col-md-3 footer-links">
            <h4>Useful Links</h4>
            <ul>
              <li><a href="{% url 'mybog:index' %}">Home</a></li>
              <li><a href="{% url 'mybog:about' %}">About us</a></li>
              <li><a href="{% url 'mybog:service' %}">Services</a></li>
              <li><a href="{% url 'mybog:contact' %}">Contact Us</a></li>
              <li><a href="{% url 'mybog:university' %}">Universities</a></li>
            </ul>
          </div><!-- End footer links column-->

          <div class="col-lg-3 col-md-3 footer-links">
            <h4>Our Services</h4>
            <ul>
              <li><a href="#">University Admissions</a></li>
              <li><a href="#">Ticket and Visa Assistance</a></li>
              <li><a href="#">Product Management</a></li>
              <li><a href="#">Travel Arrangements</a></li>
              <li><a href="#">Welfare & Monitoring</a></li>
              <li><a href="#">Education Advice</a></li>
            </ul>
          </div><!-- End footer links column-->

        </div>
      </div>
    </div>

    <div class="footer-legal text-center position-relative">
      <div class="container">
        <div class="copyright">
          &copy; <a href="{% url 'admin:index' %}">Copyright</a> <strong><span>WIBOTEC</span></strong>. All Rights Reserved
        </div>
        <div class="credits">
          Designed by <a href="https://wibotec.github.io">WIBOTEC</a>
        </div>
      </div>
    </div>

  </footer>
  <!-- End Footer -->

  <div id="preloader"></div>

  <!-- Vendor JS Files -->
  <script src="{% static 'mybog/assets/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'mybog/assets/bootstrap/js/bootstrap.bundle.js' %}"></script>
  <script src="{% static 'mybog/aos/aos.js' %}"></script>
  <script src="{% static 'mybog/glightbox/js/glightbox.min.js' %}"></script>
  <script src="{% static 'mybog/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'mybog/swiper/swiper-bundle.min.js' %}"></script>
  <script src="{% static 'mybog/purecounter/purecounter_vanilla.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'mybog/assets/js/main.js' %}"></script>
  <script src="assets/js/main.js"></script>

</body>

</html>

hcaec/mybog/templates/mybog/university.html
{% extends 'mybog/mylayout.html' %}
{% load static %}

{% block content %}

<main id="main">

    <!-- ======= Breadcrumbs ======= -->
    <div class="breadcrumbs d-flex align-items-center" style="background-image: url('assets/img/breadcrumbs-bg.jpg');">
      <div class="container position-relative d-flex flex-column align-items-center" data-aos="fade">

        <h2>Universities</h2>
        <ol>
          <li><a href="{% url 'mybog:index' %}">Home</a></li>
          <li>Universities</li>
        </ol>

      </div>
    </div><!-- End Breadcrumbs -->

    <!-- ======= Recent Blog Posts Section ======= -->
    <section id="recent-blog-posts" class="recent-blog-posts">
      <div class="container" data-aos="fade-up">
      <div class=" section-header">
        <h2>Our Universities</h2>
        <p>In commodi voluptatem excepturi quaerat nihil error autem voluptate ut et officia consequuntu</p>
      </div>

      <div class="row gy-5">

        {% for university in university %}

        <div class="col-xl-4 col-md-6" data-aos="fade-up" data-aos-delay="100">
          <div class="post-item position-relative h-100">

            <div class="post-content d-flex flex-column">

              <h3 class="post-title">{{university.universityName}}</h3>

              <div class="meta d-flex align-items-center">
                <div class="d-flex align-items-center">
                  <i class="bi bi-geo-alt"></i> <span class="ps-2">{{university.universityCountry}}</span>
                </div>
                <span class="px-3 text-black-50">/</span>
                <div class="d-flex align-items-center">
                  <i class="bi bi-folder2"></i> <span class="ps-2">{{university.universityContinent}}</span>
                </div>
              </div>

              <hr>

            </div>

          </div>
        </div><!-- End post item -->

        {% endfor %}

      </div>

      </div>
      <div class="container mt-3 d-flex justify-content-center pagination">
        {% if university.has_previous %}
          <li><a class="page-link bg-warning text-white" href="?page=1">&laquo First</a></li>
          <li><a class="page-link bg-warning text-white" href="?page={{university.previous_page_number}}">&laquo Previous</a></li>
        {% endif %}
        
        <li class="page-item page-link text-white bg-warning"> page {{university.number}} of {{university.paginator.num_pages}}</li>
  
        {% if university.has_next %}
          <li><a class="page-link bg-warning text-white" href="?page={{university.next_page_number}}">next &raquo</a></li>
          <li><a class="page-link bg-warning text-white" href="?page={{university.paginator.num_pages}}">Last &raquo</a></li>
        {% endif %}
      </div>
    </section>
    <!-- End Recent Blog Posts Section -->
  </main><!-- End #main -->


{% endblock content %}